version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - task: fmt-sheeter
      - task: fmt-cs
      - task: lint-sheeter

  # sheeter程式碼格式化
  fmt-sheeter:
    cmds:
      - gofmt -s -w -l .
      
  # client-unity格式化
  fmt-cs:
    cmds:
      - dotnet csharpier .

  # sheeter程式碼檢查
  lint-sheeter:
    cmds:
      - golangci-lint -v run

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem